server:
  port: 8080
  error.include-stacktrace: never

spring.neo4j:
  uri: neo4j+s://86d326ce.databases.neo4j.io
  authentication:
    username: neo4j
    password: xg3WKzsTOn40UaF4Sm-BgC85UW8x1OteLff-kekcU3s